In [129]:
# df = pd.read_csv('./test_data/output.csv', sep=',')

# KEYPOINT = 32
# KEYPOINT_MOD = 26

# # CSV파일 구조:
# # 액션시나리오번호_촬영순번-C카메라번호
# # 45-1_001-C3 / 0 / 키포인트


# x_data = df[['Keypoints']]
# t_data = np.zeros(96,)
# print(t_data)
# # t_data = df[['ID']]

# keypoint = np.array(x_data['Keypoints'].values)
# keypoint_arr = np.empty((0,KEYPOINT_MOD), float)

# for i in range(0, len(keypoint)) :
#     keypoint[i] = keypoint[i].replace("[", "")
#     keypoint[i] = keypoint[i].replace("]", "")
#     keypoint[i] = keypoint[i].split(',')

#     # keypoint[0]
#     nd_array = np.array(keypoint[i])
#     nd_array = nd_array.astype(np.float)
# #     print("nd_array")
# #     print(nd_array)

#     # 학습데이터는 모두 2D데이터
#     # 사용하지 않는 값과 사용할 수 없는 annotation을 제거
#     result = remove_aihub_annotation(nd_array)
# #     print(result)
# #     print(result.shape)
# #     print(type(result[0][0]))

#     keypoint_arr = np.append(keypoint_arr, result, axis=0)

# print(keypoint.shape)
# print(len(keypoint))
    
# print(type(keypoint_arr))
# print(keypoint_arr)
# print(keypoint_arr.shape)
# print(len(keypoint_arr))
# print(keypoint_arr[0])
# print(type(keypoint_arr[0])) # <class 'str'>



In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# 목표: DACON Baseline 코드를 이용해 LSTM을 활용한 학습 진행

In [130]:
import tensorflow as tf
# tf.__version__
# config = tf.ConfigProto()
# config.gpu_options.allow_growth = True
# session = tf.Session(config=config....)

# physical_devices = tf.config.list_physical_devices('GPU') 
# for device in physical_devices:
#     tf.config.experimental.set_memory_growth(device, True)

# gpus = tf.config.experimental.list_physical_devices('GPU')
# if gpus:
#     # 텐서플로가 첫 번째 GPU에 1GB 메모리만 할당하도록 제한
#     try:
#         tf.config.experimental.set_virtual_device_configuration(
#             gpus[0],
#             [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=4096)])
#     except RuntimeError as e:
#         # 프로그램 시작시에 가상 장치가 설정되어야만 합니다
#         print(e)
    

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

In [131]:
tf.config.experimental.list_physical_devices('GPU')
# physical_devices = tf.config.list_physical_devices('GPU') 
# for device in physical_devices:
#     tf.config.experimental.set_memory_growth(device, True)

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [132]:
# import pandas as pd
# import numpy as np

# train=pd.read_csv('train_features.csv')
# train_labels=pd.read_csv('train_labels.csv')
# test=pd.read_csv('test_features.csv')
# submission=pd.read_csv('sample_submission.csv')

In [133]:
# 목표: DACON Baseline 코드를 이용해 LSTM을 활용한 학습 진행

import json
import numpy as np
import pandas as pd

import io

import os
import matplotlib.image as img
import matplotlib.pyplot as plt
from tqdm import tqdm

# import tensorflow as tf
# from sklearn.linear_model import LogisticRegression
# from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
# from sklearn.neighbors import KNeighborsClassifier
# from scipy import stats

In [134]:
# def remove_aihub_annotation(keypoint):
#     # 학습데이터는 모두 2D데이터
#     # 따라서, 사용하지 않는 값 (_, _, 2)을 제거
#     keypoint = keypoint.reshape(-1, 3)
#     result = np.delete(keypoint, 2, axis=1)
    
#     # 실제 예측에서 사용할 수 없는 Annotation 제거
#     result = np.delete(result, [6,7,8], axis=0)
#     result = result.reshape(1,-1)
    
#     return result

In [135]:
# def get_keypoints_in_float(string_data):
#     keypoint = np.array(string_data['Keypoints'].values)
#     print(keypoint.shape)
#     keypoint_arr = np.empty((0,KEYPOINT_MOD), float)

# #     i=0
#     for i in tqdm(range(0, len(keypoint))) :
#         keypoint[i] = keypoint[i].replace("[", "")
#         keypoint[i] = keypoint[i].replace("]", "")
#         keypoint[i] = keypoint[i].split(',')

#         # keypoint[0]
#         nd_array = np.array(keypoint[i])
#         nd_array = nd_array.astype(np.float)
#     #     print("nd_array")
#     #     print(nd_array)
#     #     print(nd_array.shape)

#         # 학습데이터는 모두 2D데이터
#         # 사용하지 않는 값과 사용할 수 없는 annotation을 제거
#         result = remove_aihub_annotation(nd_array)
#     #     print(result)
#     #     print(result.shape)
#     #     print(type(result[0][0]))

#         keypoint_arr = np.append(keypoint_arr, result, axis=0)
#     return keypoint_arr

In [136]:
# def split_my_train_test_set(dataframe):
#     # ['Time', 'ID_TYPE', 'Keypoint', 'Answer']

#     id_data = dataframe[['ID_TYPE', 'Answer']].drop_duplicates(['ID_TYPE'])
#     id_data = id_data.reset_index(drop=True)

#     train_x_data, test_x_data, train_t_data, test_t_data = \
#     train_test_split(id_data.drop('Answer', axis=1, inplace=False),
#                      id_data['Answer'],
#                      test_size=0.3,
#                      stratify=id_data['Answer'],
#                      random_state=0)
#     train_x_data.reset_index(drop=True, inplace=True)
#     test_x_data.reset_index(drop=True, inplace=True)
#     train_t_data.reset_index(drop=True, inplace=True)
#     test_t_data.reset_index(drop=True, inplace=True)
    
#     result_train = pd.DataFrame( columns={'Time', 'ID_TYPE', 'Keypoints', 'Answer'} )
#     result_test = pd.DataFrame( columns={'Time', 'ID_TYPE', 'Keypoints', 'Answer'} )

# #     for k in tqdm(range(0, 3)):
#     for k in tqdm(range(0, len(train_x_data))):
#         pre_data = dataframe[ dataframe['ID_TYPE']==train_x_data.at[k, 'ID_TYPE'] ]
#         result_train = result_train.append(pre_data)
    
#     for k in tqdm(range(0, len(test_x_data))):
#         pre_data = dataframe[ dataframe['ID_TYPE']==test_x_data.at[k, 'ID_TYPE'] ]
#         result_test = result_test.append(pre_data)

#     result_train = result_train[['Time', 'ID_TYPE', 'Keypoints', 'Answer']]
#     result_test = result_test[['Time', 'ID_TYPE', 'Keypoints', 'Answer']]
    
#     result_train.reset_index(drop=True, inplace=True)
#     result_test.reset_index(drop=True, inplace=True)
    
#     return result_train, result_test, train_t_data, test_t_data

In [137]:
# df_original = pd.read_csv('./train/dropped_train.csv', sep=',')

# KEYPOINT = 32
# KEYPOINT_MOD = 26

# # CSV파일 구조:
# # 45-1_001-C3 / 0 / 키포인트

# # 5-7_016-C12
# # 41-9_016-C12
# # 6-7_603-C09

# # df.head(50)

# print(df_original[ df_original['Time']==8 ])

# drop_index = df_original[ df_original['Time']==8 ].index
# print(drop_index)
# # new_test_df.loc[41448]
# print(df_original.shape)

# df = df_original.drop(drop_index, inplace=False)
# df = df.reset_index(drop=True, inplace=False)

# print(df.shape)

In [138]:
# df["ID_TYPE"] = df["ID"] + "_" + df["Person"].map(str)
# df_data = df.drop(['ID', 'Person'], axis=1)
# df_data = df_data[['Time', 'ID_TYPE', 'Keypoints', 'Answer']]
# print(df_data)

In [139]:
# train_x, test_x, train_t, test_t = split_my_train_test_set(df_data)

# train_x.head(50)
# # test_x.head(50)

# print(train_x.shape)
# print(train_t.shape)

# # x_data = df[['Keypoints']]
# # t_data = np.zeros(len(x_data),)
# # print(x_data)
# # print(len(x_data))
# # print(x_data.shape)
# # # print(t_data)
# # # t_data = df[['ID']]

# # x_data_mod = get_keypoints_in_float(x_data)

# # # print(keypoint.shape)
# # # print(len(keypoint))
    
# # print(type(x_data_mod))
# # print(x_data_mod)
# # print(x_data_mod.shape)
# # print(len(x_data_mod))
# # print(x_data_mod[0])
# # print(type(x_data_mod[0])) # <class 'str'>

In [140]:
# train_x[ train_x['Time']==8 ]

In [141]:
# drop_index = train_x[ train_x['Time']==8 ].index
# print(drop_index)
# # new_test_df.loc[41448]
# print(train_x.shape)

# train_x_mod = train_x.drop(drop_index, inplace=False)
# train_x_mod = train_x_mod.reset_index(drop=True, inplace=False)

# train_t_mod = train_t.drop(drop_index, inplace=False)
# train_t_mod = train_t_mod.reset_index(drop=True, inplace=False)

# # new_test_df
# print(train_x_mod.shape)
# print(train_t_mod.shape)

In [142]:
# train_x_data = get_keypoints_in_float(train_x_mod[['Keypoints']])

# print(train_x_data.shape)

In [143]:
# # train_x_data.to_csv('./train/train_x_data.csv',  mode='w', header = True)
# # train_x_data
# # pd.DataFrame({'Keypoints': train_x_data}).to_csv('./train/train_x_data.csv',  mode='w', header = True)

# np.savetxt('./train/train_x_data.csv',train_x_data,delimiter=",")

# train_t_mod.to_csv('./train/train_t_mod.csv',  mode='w', header = True, index=False)
# train_t_mod


In [174]:
from numpy import genfromtxt

train_x_data_DF = genfromtxt('/content/drive/MyDrive/6조/train_x_train_t/train_x.csv', delimiter=',')
train_t_mod_DF = pd.read_csv('/content/drive/MyDrive/6조/train_x_train_t/train_t.csv', sep=',')

valid_x_data_DF = genfromtxt('/content/drive/MyDrive/6조/train_x_train_t/valid_x.csv', delimiter=',')
valid_t_mod_DF = pd.read_csv('/content/drive/MyDrive/6조/train_x_train_t/valid_t.csv', sep=',')

test_x_data_DF = genfromtxt('/content/drive/MyDrive/6조/train_x_train_t/test_x.csv', delimiter=',')
test_t_mod_DF = pd.read_csv('/content/drive/MyDrive/6조/train_x_train_t/test_t.csv', sep=',')
# print(train_x_data_DF)
# print(train_x_data_DF.shape)
# print(train_t_mod_DF)

train_x_data = train_x_data_DF
train_t_mod = train_t_mod_DF

valid_x_data = valid_x_data_DF
valid_t_mod = valid_t_mod_DF

test_x_data = test_x_data_DF
test_t_mod = test_t_mod_DF

print(train_x_data)
print(train_x_data.shape)
print(type(train_x_data[0][0]))
print(train_t_mod.shape)

print(valid_x_data)
print(valid_x_data.shape)
print(type(valid_x_data[0][0]))
print(valid_t_mod.shape)

[[ 940.  648.  958. ...  414. 1044.  470.]
 [ 940.  643.  966. ...  414. 1079.  479.]
 [1014.  628. 1005. ...  413. 1061.  469.]
 ...
 [ 904.  963.  929. ...  508. 1013.  683.]
 [ 904.  963.  929. ...  508. 1013.  683.]
 [ 904.  963.  929. ...  508. 1013.  683.]]
(97904, 26)
<class 'numpy.float64'>
(12238, 1)
[[ 920.  844.  915. ...  549.  821.  512.]
 [ 920.  844.  901. ...  587.  790.  643.]
 [ 746.  844.  784. ...  562.  798.  627.]
 ...
 [1113.  597. 1105. ...  324.  990.  394.]
 [1120.  602. 1106. ...  338.  991.  396.]
 [1120.  602. 1127. ...  344. 1026.  408.]]
(41960, 26)
<class 'numpy.float64'>
(5245, 1)


In [175]:
import easydict
 
args = easydict.EasyDict({
        "batchsize": 1,
        "epoch": 1,
#         "gpu": 0,
        "out": "result",
        "resume": False,
#         "unit": 1000,
        "validationsplit": 0.2,
        "optimizer": "rmsprop",
        "frame": 8,
#         "optimizer": "Adam",
        
})

In [158]:
# print(train_x_data.shape)
# temp = train_x_data.reshape(-1, args.frame, 26)
# print(type(temp))

In [176]:
# [ -1, (한번에 들어갈 입력값 수), (좌표개수) ]
# 13개의 x,y 좌표이므로 26개
train_x = tf.reshape(train_x_data,[-1, args.frame, 26])
train_x.shape

TensorShape([12238, 8, 26])

In [177]:
train_t_mod.shape
# print(type(train_t_mod[0]))
# print(type(train_x_data[0][0]))

(12238, 1)

In [184]:
train_t = tf.reshape(train_t_mod,[-1,1])
train_t.shape

TensorShape([12238, 1])

In [185]:
val_x = tf.reshape(valid_x_data,[-1, args.frame, 26])
val_t = tf.reshape(valid_t_mod,[-1,1])

In [186]:
test_x = tf.reshape(test_x_data,[-1, args.frame, 26])
test_t = tf.reshape(test_t_mod,[-1,1])

In [181]:
from keras.layers import Dense, LSTM, Conv1D, MaxPooling1D, Dropout, Flatten, BatchNormalization, Input, Convolution2D, Activation,TimeDistributed
from keras.layers import Input, multiply, concatenate, Activation, Masking, Reshape
from keras.layers import GlobalAveragePooling1D, Permute, Dropout
from keras.models import Sequential, Model

def generate_model():
    ip = Input(shape=(args.frame,26))

    x = Masking()(ip)
    x = LSTM(units = 50, return_sequences = True)(x)
    x = LSTM(units=50)(x)
    x = Dropout(0.3)(x)

  
    y = Reshape((208, 1))(ip)
    y = Conv1D (kernel_size=3, filters=128, strides=3, padding='valid',kernel_initializer='he_uniform')(y)
    y = BatchNormalization()(y)
    y = Activation('relu')(y)

    
    y = Conv1D (kernel_size=3, filters=128, padding='same', kernel_initializer='he_uniform')(y)
    y = BatchNormalization()(y)
    y = Activation('relu')(y)
    y = MaxPooling1D(pool_size=3, strides=3)(y)
   
    y = Conv1D (kernel_size=3, filters=128, padding='same', kernel_initializer='he_uniform')(y)
    y = BatchNormalization()(y)
    y = Activation('relu')(y)
    y = MaxPooling1D(pool_size=3, strides=3)(y)
    
    y = Conv1D (kernel_size=3, filters=256, padding='same', kernel_initializer='he_uniform')(y)
    y = BatchNormalization()(y)
    y = Activation('relu')(y)
    y = MaxPooling1D(pool_size=3, strides=3)(y) 

  
    y = Conv1D (kernel_size=3, filters=256, padding='same', kernel_initializer='he_uniform')(y)
    y = BatchNormalization()(y)
    y = Activation('relu')(y)
    y = MaxPooling1D(pool_size=2, strides=2)(y) 
     
   
    y = Dropout(0.2)(y)
    y = Flatten()(y)
    
    x = concatenate([x, y])

    out = Dense(1, activation='sigmoid')(x)
    

    model = Model(ip, out)
    #model.summary()
    return model
model = generate_model()
model.summary()

Model: "model_44"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_75 (InputLayer)          [(None, 8, 26)]      0           []                               
                                                                                                  
 reshape_60 (Reshape)           (None, 208, 1)       0           ['input_75[0][0]']               
                                                                                                  
 conv1d_289 (Conv1D)            (None, 69, 128)      512         ['reshape_60[0][0]']             
                                                                                                  
 batch_normalization_282 (Batch  (None, 69, 128)     512         ['conv1d_289[0][0]']             
 Normalization)                                                                            

In [26]:
# #가벼운 모델 생성
# model = Sequential()
# model.add(LSTM(32, input_shape=(args.frame,26)))
# model.add(Dense(128, activation='relu'))
# model.add(Dense(64, activation='relu'))
# model.add(Dense(61, activation='softmax')) # 다중 분류
# model.add(Dense(1, activation='sigmoid'))

# # Adam 최적화함수를 사용해보는 것도 고려해볼 것
# # model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy']) # 다중 분류
# model.compile(optimizer=args.optimizer, loss='binary_crossentropy', metrics=['accuracy'])

In [182]:
num_models = 1
model_list=[]

for i in tqdm(range(num_models)):
    model = generate_model()
    model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
    model.fit(train_x, train_t, epochs=15, batch_size=32,validation_data=(val_x, val_t))
    model_list.append(model)

# model.save(f"model_{i}.h5")

  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1/15
383/383 [==============================] - 26s 39ms/step - loss: 0.4408 - accuracy: 0.7904 - val_loss: 0.3953 - val_accuracy: 0.8219
Epoch 2/15
383/383 [==============================] - 12s 30ms/step - loss: 0.3509 - accuracy: 0.8412 - val_loss: 0.5681 - val_accuracy: 0.7676
Epoch 3/15
383/383 [==============================] - 12s 31ms/step - loss: 0.3070 - accuracy: 0.8645 - val_loss: 0.4293 - val_accuracy: 0.8069
Epoch 4/15
383/383 [==============================] - 12s 31ms/step - loss: 0.2715 - accuracy: 0.8827 - val_loss: 0.3073 - val_accuracy: 0.8667
Epoch 5/15
383/383 [==============================] - 12s 31ms/step - loss: 0.2409 - accuracy: 0.8991 - val_loss: 0.2839 - val_accuracy: 0.8791
Epoch 6/15
383/383 [==============================] - 12s 30ms/step - loss: 0.2187 - accuracy: 0.9088 - val_loss: 0.2865 - val_accuracy: 0.8848
Epoch 7/15
383/383 [==============================] - 12s 31ms/step - loss: 0.1980 - accuracy: 0.9176 - val_loss: 0.3184 - val_accuracy:

100%|██████████| 1/1 [03:34<00:00, 214.56s/it]


In [166]:
import keras

new_model = tf.keras.models.load_model('/content/drive/MyDrive/6조/model_0.h5')

new_model.summary()

Model: "model_41"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_72 (InputLayer)          [(None, 8, 26)]      0           []                               
                                                                                                  
 reshape_57 (Reshape)           (None, 208, 1)       0           ['input_72[0][0]']               
                                                                                                  
 conv1d_274 (Conv1D)            (None, 69, 128)      512         ['reshape_57[0][0]']             
                                                                                                  
 batch_normalization_267 (Batch  (None, 69, 128)     512         ['conv1d_274[0][0]']             
 Normalization)                                                                            

In [188]:
loss, mse = model.evaluate(test_x, test_t, batch_size=1)
print('acc : ', mse)

7494/7494 [==============================] - 66s 8ms/step - loss: 0.1866 - accuracy: 0.9347
acc :  0.9347478151321411


In [190]:
y_predict = model.predict(test_x)
print(y_predict)

[[5.6515366e-04]
 [9.9965429e-01]
 [2.0504068e-01]
 ...
 [6.2665808e-01]
 [9.6797413e-01]
 [9.9875641e-01]]
