In [7]:
# 목표: DACON Baseline 코드를 이용해 LSTM을 활용한 학습 진행

import json
import numpy as np
import pandas as pd

import io

import os
import matplotlib.image as img
import matplotlib.pyplot as plt
from tqdm import tqdm

In [3]:
def remove_aihub_annotation(keypoint):
    # 학습데이터는 모두 2D데이터
    # 따라서, 사용하지 않는 값 (_, _, 2)을 제거
    keypoint = keypoint.reshape(-1, 3)
    result = np.delete(keypoint, 2, axis=1)
    
    # 실제 예측에서 사용할 수 없는 Annotation 제거
    result = np.delete(result, [6,7,8], axis=0)
    result = result.reshape(1,-1)
    
    return result

In [79]:
df = pd.read_csv('./test_data/output.csv', sep=',')

KEYPOINT = 32
KEYPOINT_MOD = 26

# CSV파일 구조:
# 액션시나리오번호_촬영순번-C카메라번호
# 45-1_001-C3 / 0 / 키포인트


x_data = df[['Keypoints']]
t_data = np.zeros(96,)
print(t_data)
# t_data = df[['ID']]

keypoint = np.array(x_data['Keypoints'].values)
keypoint_arr = np.empty((0,KEYPOINT_MOD), float)

for i in range(0, len(keypoint)) :
    keypoint[i] = keypoint[i].replace("[", "")
    keypoint[i] = keypoint[i].replace("]", "")
    keypoint[i] = keypoint[i].split(',')

    # keypoint[0]
    nd_array = np.array(keypoint[i])
    nd_array = nd_array.astype(np.float)
#     print("nd_array")
#     print(nd_array)

    # 학습데이터는 모두 2D데이터
    # 사용하지 않는 값과 사용할 수 없는 annotation을 제거
    result = remove_aihub_annotation(nd_array)
#     print(result)
#     print(result.shape)
#     print(type(result[0][0]))

    keypoint_arr = np.append(keypoint_arr, result, axis=0)

print(keypoint.shape)
print(len(keypoint))
    
print(type(keypoint_arr))
print(keypoint_arr)
print(keypoint_arr.shape)
print(len(keypoint_arr))
print(keypoint_arr[0])
print(type(keypoint_arr[0])) # <class 'str'>



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(96,)
96
<class 'numpy.ndarray'>
[[ 960.   585.   969.  ...  414.   960.   411. ]
 [1252.   664.  1256.  ...  507.  1202.   515. ]
 [ 928.   654.   944.  ...  469.   943.   464. ]
 ...
 [ 786.   613.   731.5 ...  437.   807.   486. ]
 [ 756.   635.   737.  ...  420.   745.   420. ]
 [ 830.   863.   834.  ...  597.   864.   639. ]]
(96, 26)
96
[ 960.  585.  969.  519.  994.  455.  994.  459.  994.  525. 1035.  594.
  985.  317.  972.  411.  988.  418.  997.  380.  988.  377.  978.  414.
  960.  411.]
<class 'numpy.ndarray'>


In [14]:
df = pd.read_csv('./test_data/5.csv', sep=',')

KEYPOINT = 32
KEYPOINT_MOD = 26

# CSV파일 구조:
# 45-1_001-C3 / 0 / 키포인트

# 5-7_016-C12
# 41-9_016-C12
# 6-7_603-C09

def get_keypoints_in_float(string_data):
    keypoint = np.array(string_data['Keypoints'].values)
    print(keypoint.shape)
    keypoint_arr = np.empty((0,KEYPOINT_MOD), float)

#     i=0
    for i in tqdm(range(0, len(keypoint))) :
        keypoint[i] = keypoint[i].replace("[", "")
        keypoint[i] = keypoint[i].replace("]", "")
        keypoint[i] = keypoint[i].split(',')

        # keypoint[0]
        nd_array = np.array(keypoint[i])
        nd_array = nd_array.astype(np.float)
    #     print("nd_array")
    #     print(nd_array)
    #     print(nd_array.shape)

        # 학습데이터는 모두 2D데이터
        # 사용하지 않는 값과 사용할 수 없는 annotation을 제거
        result = remove_aihub_annotation(nd_array)
    #     print(result)
    #     print(result.shape)
    #     print(type(result[0][0]))

        keypoint_arr = np.append(keypoint_arr, result, axis=0)
    return keypoint_arr


x_data = df[['Keypoints']]
t_data = np.zeros(len(x_data),)
print(x_data)
print(len(x_data))
print(x_data.shape)
# print(t_data)
# t_data = df[['ID']]

x_data_mod = get_keypoints_in_float(x_data)

# print(keypoint.shape)
# print(len(keypoint))
    
print(type(x_data_mod))
print(x_data_mod)
print(x_data_mod.shape)
print(len(x_data_mod))
print(x_data_mod[0])
print(type(x_data_mod[0])) # <class 'str'>

                                               Keypoints
0      [967.0, 652.0, 2.0, 981.0, 575.0, 2.0, 991.0, ...
1      [949.0, 657.0, 2.0, 947.0, 582.0, 2.0, 955.0, ...
2      [970.0, 649.0, 2.0, 995.0, 575.0, 2.0, 1006.0,...
3      [950.0, 656.0, 2.0, 939.0, 582.0, 2.0, 940.0, ...
4      [1037.0, 649.0, 2.0, 1037.0, 572.0, 2.0, 1036....
...                                                  ...
52077  [930.0, 738.0, 2.0, 921.0, 649.0, 2.0, 913.0, ...
52078  [1100.0, 713.0, 2.0, 1051.0, 627.0, 2.0, 1018....
52079  [930.0, 734.0, 2.0, 913.0, 649.0, 2.0, 888.0, ...
52080  [1108.0, 721.0, 2.0, 1087.0, 627.0, 2.0, 1056....
52081  [910.0, 737.0, 2.0, 879.0, 654.0, 2.0, 846.0, ...

[52082 rows x 1 columns]
52082
(52082, 1)
(52082,)


100%|███████████████████████████████████| 52082/52082 [00:25<00:00, 2018.85it/s]


<class 'numpy.ndarray'>
[[ 967.  652.  981. ...  389. 1095.  371.]
 [ 949.  657.  947. ...  445.  869.  497.]
 [ 970.  649.  995. ...  467. 1096.  505.]
 ...
 [ 930.  734.  913. ...  499.  906.  548.]
 [1108.  721. 1087. ...  468. 1059.  521.]
 [ 910.  737.  879. ...  505.  844.  541.]]
(52082, 26)
52082
[ 967.  652.  981.  575.  991.  484. 1030.  486. 1044.  578. 1061.  652.
 1009.  333.  938.  333.  963.  362.  984.  393. 1037.  400. 1069.  389.
 1095.  371.]
<class 'numpy.ndarray'>


In [80]:
import pandas as pd
import numpy as np

# train=pd.read_csv('train_features.csv')
# train_labels=pd.read_csv('train_labels.csv')
# test=pd.read_csv('test_features.csv')
# submission=pd.read_csv('sample_submission.csv')

In [ ]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [ ]:
import easydict
 
args = easydict.EasyDict({
        "batchsize": 128,
        "epoch": 38,
#         "gpu": 0,
        "out": "result",
        "resume": False,
#         "unit": 1000,
        "validationsplit": 0.2,
        "optimizer": "rmsprop",
#         "optimizer": "Adam",
        
})

In [ ]:
# [ -1, (한번에 들어갈 입력값 수), (좌표개수) ]
# 13개의 x,y 좌표이므로 26개
X=tf.reshape(np.array(train.iloc[:,2:]),[-1, 19, 26])
X.shape

In [ ]:
y = tf.keras.utils.to_categorical(train_labels['label']) 
y.shape

In [ ]:
#가벼운 모델 생성
model = Sequential()
model.add(LSTM(32, input_shape=(19,26)))
model.add(Dense(128, activation='relu'))
# model.add(Dense(61, activation='softmax')) # 다중 분류
model.add(Dense(61, activation='sigmoid'))

# Adam 최적화함수를 사용해보는 것도 고려해볼 것
# model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy']) # 다중 분류
model.compile(optimizer=args.optimizer, loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(X,y, epochs=args.epoch, batch_size=args.batchsize, validation_split=0.2)

In [ ]:
test_X=tf.reshape(np.array(test.iloc[:,2:]),[-1, 19, 26])
test_X.shape

In [ ]:
prediction=model.predict(test_X)

In [ ]:
prediction.shape